name: Core Application E2E Tests commit
permissions:
  contents: read
  pull-requests: write
# on:
#   workflow_dispatch:
#     inputs:
#       c8Version:
#         description: "C8 Version"
#         required: true
on:
  push:

jobs: # github.event.inputs.c8Version replaced
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      services_ready: ${{ steps.wait-for-services.outputs.ready }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            software-properties-common

          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

          DOCKER_COMPOSE_VERSION="v2.20.0"
          sudo curl -SL https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set DATABASE environment variable
        run: |
          echo "DATABASE=elasticsearch" >> $GITHUB_ENV

      - name: Start Tasklist and Operate
        run: |
          DATABASE=elasticsearch docker compose up -d tasklist operate
        working-directory: qa/core-application-e2e-test-suite/config

      # - name: Check logs for Tasklist service
      #   run: |
      #     echo "== Tasklist Logs =="
      #     docker-compose logs -f tasklist
      #   working-directory: qa/core-application-e2e-test-suite/config

      - name: Check logs for Tasklist and Operate in the background
        run: |
          docker-compose logs tasklist &  # Run tasklist logs in the background
          docker-compose logs operate &   # Run operate logs in the background
          wait  # Wait for both background processes to finish
        working-directory: qa/core-application-e2e-test-suite/config

      - name: Check if services are healthy
        run: |
          curl -s http://localhost:8080/health || exit 1
          curl -s http://localhost:8081/health || exit 1

      # - name: Wait for services to be ready
      #   id: wait-for-services
      #   run: |
      #     echo "Checking if services are up..."
      #     for i in {1..30}; do
      #       if curl -s http://localhost:8080/health | grep '"status":"UP"' && \
      #          curl -s http://localhost:8081/health | grep '"status":"UP"'; then
      #         echo "Services are ready!"
      #         echo "ready=true" >> $GITHUB_OUTPUT
      #         exit 0
      #       fi
      #       echo "Waiting for services... ($i/30)"
      #       sleep 10
      #     done
      #     echo "Services failed to start in time."
      #     exit 1
      - name: Wait for services to be ready
        id: wait-for-services
        run: |
          echo "Checking if services are up..."
          for i in {1..60}; do
            response_8080=$(curl -s http://localhost:8080/health)
            response_8081=$(curl -s http://localhost:8081/health)
            if echo "$response_8080" | grep '"status":"UP"' && echo "$response_8081" | grep '"status":"UP"'; then
              echo "Services are ready!"
              echo "ready=true" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "Waiting for services... ($i/60)"
            echo "Response from 8080: $response_8080"
            echo "Response from 8081: $response_8081"
          sleep 10
           done
          echo "Services failed to start in time."
          exit 1

  core-component-tests:
    needs: setup-environment
    runs-on: ubuntu-latest
    if: needs.setup-environment.outputs.services_ready == 'true'
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        project: ["chromium"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: qa/core-application-e2e-test-suite/package-lock.json

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --verbose  # Adding verbose flag to show more detailed logs
        working-directory: qa/core-application-e2e-test-suite

      - name: Run tests
        uses: ./.github/actions/core-application-e2e-test-suite
